### ISSUE TITLE
Why the Youtube meetings were public but not anymore?

### ISSUE THREAD

**Issue by a0viedo** [node-forward/discussions#8]
At least the ones at [Oct 3](https://www.youtube.com/watch?v=X5PtRHjUO1U) and [Oct 9](https://www.youtube.com/watch?v=fNW_tu2QnpA).

**Comment by bnoordhuis** [comment]
@rvagg I saw you uploaded the video to YouTube.  Has it been published yet?

**Comment by rvagg** [comment]
Yes, its accessible but unlisted. Link is in the email thread about it. I just didn't want to be the one to share it here _yet_ given the sensitivities of the current situation and seeing how the previous ones we're temporarily unlisted. If you want to share it, go ahead, though it might make sense to wait until some dust settles. @mikeal?

To everyone else reading this: it's probably frustrating watching this semi-closed and not well communicated process but please be aware that everyone involved here is working together towards and better future for Node, one that's also much more inclusive and open, and involves things like public recordings of TC meetings. There's just some sensitive politiking going on on our way there.

**Comment by mbonaci** [comment]
@rvagg :+1:  for the initiative, but what dust? 
We don't know shit, so the explanation is rather useless :)

I cannot fathom what could be the reason for making those videos private?
Open all the things! Say it loud and clear.

Just my uninformed guess:
http://youtu.be/-zRN7XLCRhc
So fork, yeah, but tell us what's going on.

**Comment by a0viedo** [comment]
"forkphobia", that's an awesome term introduced by @bcantrill

**Comment by dshaw** [comment]
"forkaphilic" too. https://twitter.com/bcantrill/status/520649394681421824

**Comment by mbonaci** [comment]
@rvagg @dshaw @mikeal so there's still no explanation about what's going on? 
Aren't node community supposed to be open in every possible way (as open mind, not as open window :) 
Can you at least give us a good reason why you made this look like an elitist gathering, conspiring behind a closed door?

I'm not trolling, I genuinely feel that way. I'm writing this because I care.
It pisses me off that I'm almost in a complete dark.

I was very surprised to see that you made videos (anything) private.
I expected to see the whole story after Joyent formed advisory board. Nothing happened.
I expected to get some info from the last nodeup. Nothing there.

Couple of private videos, tablespoon of mysterious "dust settling" and a pinch of "sensitivities of the current situation". What a hell?

I would have never expected this kind of behavior from the node community rock stars!?!

Now please, would you be so kind to ignore me a bit more, it feels so welcoming :(
You can throw away all those "noobs welcome" efforts, as long as things like this are happening.

Would you feel welcome?

**Comment by Albert-IV** [comment]
@mbonaci Calm down man, I don't think anyone is deliberately snubbing you here.  I think there are some legalities and political maneuvering going on that can't be made public yet, and I don't think making a scene will help.

Best advice I can give you is to watch this repo, as well as the node repo.  Keep up with the issue trackers on both.  Keeping up with the issues and fixes should give you a better idea on where the node.js project is going.

There have been some hints that v12 will be getting released in the next few weeks, which I'd imagine would clear some of this mystery up.  That being said I'm in the dark about all of this as well, so we're all waiting to find out what's happening.

**Comment by ijroth** [comment]
You may want to listen to the next Joyent advisory board meeting: 

https://nodejs.org/advisory-board/2014-11-06/minutes.html#minutes_md_next_meeting

**Comment by mbonaci** [comment]
@droppedoncaprica so you're in the dark too and that doesn't bother you?
OK, but please allow that it bothers me.
Can I express my honest opinion without being accused of making a scene?

So if someone explained what's going on, she/he could be sued? Come on, really? 
Can someone "that's not in the dark" confirm that?
That would certainly be a viable explanation, but it seems a bit stretched.

Thanks @droppedoncaprica though, for at least trying to clarify.
Thanks @ijroth.

**Comment by mbonaci** [comment]
@domenic you don't mean sued for laying down the facts?

Thanks for that, but you'll understand that this is just another hint in the long line of hints about something that is very important to me.

**Comment by mikeal** [comment]
I've sent the Nodejs Advisory Board a pull request with the governance and contribution policy adopted by Node Forward.

https://github.com/joyent/nodejs-advisory-board/pull/11

This is now in the public and all of you have a chance to participate and support to hate on that policy.

**Comment by a0viedo** [comment]
Closing, it's not relevant anymore.
